# Generated by Django 5.2.8 on 2025-12-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='about_decription',
            new_name='about_description',
        ),
    ]
